# Generated by Django 4.0.6 on 2022-07-12 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('ingredients', models.CharField(max_length=100)),
                ('utensils', models.CharField(max_length=100)),
                ('directions', models.CharField(max_length=100)),
                ('preptime', models.FloatField(max_length=100)),
                ('cooktime', models.FloatField(max_length=100)),
                ('cooksetting', models.CharField(max_length=100)),
                ('calories', models.IntegerField(max_length=100)),
                ('rating', models.IntegerField(max_length=100)),
            ],
            options={
                'ordering': ['name', 'rating'],
            },
        ),
    ]
