# Generated by Django 4.0.6 on 2022-08-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0007_alter_recipe_rating_alter_recipereview_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=13),
        ),
        migrations.AlterField(
            model_name='recipereview',
            name='review_rating',
            field=models.DecimalField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], decimal_places=1, max_digits=13),
        ),
    ]
